name: clinexchange
description: "ClinExchange is a mobile application designed to facilitate group-based savings and lending, commonly known as *rotating savings and credit associations* (ROSCAs)."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  firebase_core: ^3.4.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  dio: ^5.7.0
  get_it: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/images/auth/
    - assets/vectors/common/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
