// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA81soBTFCDCubZTyHKRUauE9LEaRpQN3A',
    appId: '1:370981434067:web:50b2e7ebb8c371fe381a26',
    messagingSenderId: '370981434067',
    projectId: 'clinexchange',
    authDomain: 'clinexchange.firebaseapp.com',
    storageBucket: 'clinexchange.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN9ZwOugeLcX-IWLDCzh7UjHMbLW-w9BU',
    appId: '1:370981434067:android:b41268db75d3393c381a26',
    messagingSenderId: '370981434067',
    projectId: 'clinexchange',
    storageBucket: 'clinexchange.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-KcwkFk6id7Xq8_gDDpUTYMduv9xvOqA',
    appId: '1:370981434067:ios:dc49ff4b06e500d4381a26',
    messagingSenderId: '370981434067',
    projectId: 'clinexchange',
    storageBucket: 'clinexchange.appspot.com',
    iosBundleId: 'com.clinton.clinexchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-KcwkFk6id7Xq8_gDDpUTYMduv9xvOqA',
    appId: '1:370981434067:ios:dc49ff4b06e500d4381a26',
    messagingSenderId: '370981434067',
    projectId: 'clinexchange',
    storageBucket: 'clinexchange.appspot.com',
    iosBundleId: 'com.clinton.clinexchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA81soBTFCDCubZTyHKRUauE9LEaRpQN3A',
    appId: '1:370981434067:web:a4a12bbd2ea8705b381a26',
    messagingSenderId: '370981434067',
    projectId: 'clinexchange',
    authDomain: 'clinexchange.firebaseapp.com',
    storageBucket: 'clinexchange.appspot.com',
  );
}
